#!/usr/bin/env bash

cd "$(tmux run "echo #{pane_start_path}")" || exit
url=$(git remote get-url origin)

if [[ $url == *github.com* ]]; then
    if [[ $url == git@* ]]; then
        url="${url#git@}"
        url="${url/:/\/}"
        url="https://$url"
    fi

    if grep -qi microsoft /proc/version 2>/dev/null; then
        # WSL detected
        wslview "$url"
    else
        # Native Linux
        xdg-open "$url"
    fi
else
    echo "This repository is not hosted on GitHub"
fi

