#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# Contributors:     Eb
# Project name:     tmks

# Version:          0.1

# Description:
# Uses fzf to kill tmux sessions

# Dependencies:
# - tmux
# - fzf

# Date created:     01/11/2023
# Last updated:     01/11/2023
# ----------------------------------------------------------------------------

SELECTED_SESSIONS=$(tmux list-sessions -F "#S" | fzf-tmux -m -p 80%,60% --prompt=" " --header="Which tmux session do you want to kill?" --header-first)

if [ -n "$SELECTED_SESSIONS" ]; then
    # Set the IFS to \n to iterate over \n delimited sessions
    IFS=$'\n'
    for SESSION in $SELECTED_SESSIONS; do
        tmux kill-session -t "$SESSION"
    done
fi
