#!/usr/bin/env bash

###############################################################
# Tmux FZF List
###############################################################

SESSION=$(tmux list-sessions | fzf-tmux -m -p 80%,60% --prompt=" " --header="Active tmux sessions:" --header-first)

if [[ -z $SESSION ]]; then
    exit 1
fi

if [ "$SESSION" -eq 0 ]; then
    echo -e "\n${SESSION}"
fi
exit 0
