#!/usr/bin/env bash

###############################################################
# Tmux FZF Switch
###############################################################

SESSION=$(tmux list-sessions -F "#S" | fzf-tmux -p 80%,60% --prompt=" " --header="Switch tmux session:" --header-first)

if [ -n "$TMUX" ]; then
    tmux switch-client -t "$SESSION"
else
    tmux attach-session -t "$SESSION"
fi
