#!/bin/bash

function ip_address() {

    # Loop through the interfaces and check for the interface that is up.
    for file in /sys/class/net/*; do

        iface=$(basename $file);

        read status < $file/operstate;

        # [ "$status" == "up" ] && ip addr show $iface | awk '/inet /{printf $2" "}'
        [ "$status" == "up" ] && ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}'

    done

}

main ()
{
    ip_address
}

main
