#!/bin/bash
# ----------------------------------------------------------------------------
# Contributors:     Eb
# Project name:     tmux-man

# Version:          0.1

# Description:
# opens the man page in a tmux split or tmux window.

# Dependencies:
# - tmux
# - fzf
# - man

# Date created:     30/06/2023
# Last updated:     30/06/2023
# ----------------------------------------------------------------------------

set -euo pipefail

FILE=$(apropos . | \
    awk '{$2=""; print$0}' | \
    sed 's/  -/ -/g' | \
    fzf-tmux -m -p 80%,60% \
    --prompt=" " --header="Which manpages would you like to view?" \
    --header-first )

FILENAME=$(echo "$FILE" | awk '{print $1}')

check_deps() {
    if ! hash "$1" 2>/dev/null; then
        echo "Error: This script requires $1!"
        echo "Error: Please Install $1 using your distribution's package manager"
        notify-send \
            -t 5000 "Error: This script requires $1"
        exit 1
    fi
}

get_options ()
{
    echo "Split"
    echo "Window"
}

rename_window ()
{
    tmux rename-window -t man man-"$1"
}

open_in_window ()
{
    tmux new-window man "$1"
}

open_in_split ()
{
    tmux split-window -h -f -l 50% man "$1"
}

main ()
{
    check_deps tmux
    check_deps fzf

    CHOICE=$(get_options | \
        fzf-tmux -m -p 80%,60% \
        --prompt=" " --header="Where would you like to view the manpages?" \
        --header-first)

    case "$CHOICE" in
        Split)
            open_in_split "$FILENAME"
            exit 0
            ;;
        Window)
            open_in_window "$FILENAME"
            rename_window "$FILENAME"
            exit 0
            ;;
        *)
            echo "invalid selection"
            exit 1
            ;;
    esac
}

main
