#!/bin/bash

function ip_address() {

    # Loop through the interfaces and check for the interface that is up.
    for file in /sys/class/net/*; do

        iface=$(basename "$file");

        read -r status < "$file"/operstate;

        [ "$status" == "up" ] && ip addr show "$iface" | awk '/inet /{printf $2" "}'

    done

}

main ()
{
    ip_address
}

main
