#!/bin/bash
# ----------------------------------------------------------------------------
# Contributors:     Eb
# Project name:     tmux-nvim

# Version:          0.1

# Description:
# opens a tmux split with the selected file in nvim

# Dependencies:
# - nvim
# - tmux

# Date created:     30/06/2023
# Last updated:     30/06/2023
# ----------------------------------------------------------------------------

set -o errexit

# NOTE: I do not fully understand the find command below, but it works.
# SOURCE: https://unix.stackexchange.com/questions/468734/find-exclude-path-containing-specific-files
FILE=$(find . -maxdepth 3 -path ./.git -prune -o -print | \

        fzf-tmux -m \
        -p 80%,60% \
        --prompt=" " \
        --header="Open file in NVIM:" \
    --header-first)

if [ -n "$TMUX" ]; then
    tmux splitw -bv -l 70% nvim "$FILE"
else
    notify-send \
        -t 1500 \
        "Error" \
        "Not in a tmux session"
    exit 1
fi

# TODO:
# - Create error checking to exit properly. It currently shows an error code based on the first line of this script
