#!/usr/bin/env bash

# List tmux windows in the format: "index name"
windows=$(tmux list-windows -F '#{window_index} #{window_name}' | sed '/^$/d')

# Run fzf on the window list
selected=$(echo "$windows" | \
    fzf-tmux --reverse \
        -p 60%,50% \
        --header '󱇛  Jump to a TMUX window' \
        --prompt='  ' \
        --color border:#7DAEA3 \
        --preview "echo {} | cut -d' ' -f1 | xargs -I{} tmux capture-pane -e -t {} -p" \
        --preview-window='right:60%' \
        --preview-window=nohidden \
        --bind 'ctrl-d:execute(echo {} | cut -d" " -f1 | xargs tmux kill-window -t)+abort')

# If user selected a window, extract index and jump
if [[ -n "$selected" ]]; then
    index=$(echo "$selected" | cut -d' ' -f1)
    tmux select-window -t "$index"
fi
