#!/bin/bash

DIR=$(tmux display-message -p -F "#{pane_current_path}");

cd "$DIR" || exit

if [ -d .git ]; then
    echo -e "Working directory: $DIR\n"
else
    git rev-parse --git-dir 2> /dev/null;
fi;

# NOTE: My custom git helper script, must be in path to work. In my case ~/.local/bin
gh
