#!/usr/bin/env bash
#
# sesh connect "$(
#     sesh list -t | fzf-tmux -p 70%,50% \
    #         --no-sort --ansi --border-label ' sesh ' --prompt '  ' \
    #         --header '  ^t tmux  ^x zoxide  ^d kill  ^f find  ^g configs  ^r root' \
    #         --color border:#7DAEA3 \
    #         --bind 'tab:down,btab:up' \
    #         --bind 'ctrl-t:change-prompt(  )+reload(sesh list -t)' \
    #         --bind 'ctrl-g:change-prompt(  )+reload(sesh list -c)' \
    #         --bind 'ctrl-x:change-prompt(  )+reload(sesh list -z)' \
    #         --bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    #         --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(  )+reload(sesh list -t)' \
    #         --bind 'ctrl-r:change-prompt(  )+reload(fd --type d . "$(echo $(sesh root) | sed "s|^~|$HOME|;s|_|.|")")' \
    #         --bind 'ctrl-p:preview-half-page-up,ctrl-n:preview-half-page-down' \
    #         --preview-window 'right:60%' \
    #         --preview 'sesh preview {}' \
    #         --preview-window=hidden
#         # --preview-window=nohidden
# )"

sesh connect "$(
    sesh list -t --icons | fzf-tmux -p 70%,50% \
        --no-sort --ansi --border-label ' sesh ' --prompt '  ' \
        --color border:#7DAEA3 \
        --header 'Sessions'\
        --header-first \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-t:change-prompt(  )+change-header(Sessions)+reload(sesh list -t --icons)' \
        --bind 'ctrl-g:change-prompt(  )+change-header(Custom)+reload(sesh list -c --icons)' \
        --bind 'ctrl-x:change-prompt(  )+change-header(Zoxide)+reload(sesh list -z --icons)' \
        --bind 'ctrl-f:change-prompt(  )+change-header(Find)+reload(fd -H -d 2 -t d -E .Trash . ~)' \
        --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-header(Kill Session)+change-prompt(  )+reload(sesh list -t --icons)' \
        --bind 'ctrl-p:preview-half-page-up,ctrl-n:preview-half-page-down' \
        --preview-window 'right:60%' \
        --preview 'sesh preview {}' \
        # --preview-window=hidden
        # --preview-window=nohidden
)"
