#!/bin/bash

function get_main_ip() {
    # If running in WSL 2, /proc/version will contain "Microsoft"
    if grep -qEi "(microsoft|wsl)" /proc/version &> /dev/null; then
        # We're in WSL, so use eth0 (the WSL interface)
        ip -4 addr show eth0 | awk '/inet / {split($2,a,"/"); print a[1]}' | head -n1
    else
        # Regular Linux: Get IP from the first non-loopback, non-virtual, non-docker interface
        ip -o -4 addr show scope global | awk '!/docker|br-|virbr|vmnet|veth/ && $2 != "lo" {split($4,a,"/"); print a[1]}' | head -n1
    fi
}

main () {
    get_main_ip
}

main
