#!/usr/bin/env bash

sesh connect "$(
    sesh list -t | fzf-tmux -p 60%,50% \
        --no-sort --ansi --border-label ' sesh ' --prompt '  ' \
        --header '  ^t tmux  ^x zoxide  ^d kill  ^f find  ^g configs ' \
        --color border:#7DAEA3 \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-t:change-prompt(  )+reload(sesh list -t)' \
        --bind 'ctrl-g:change-prompt(  )+reload(sesh list -c)' \
        --bind 'ctrl-x:change-prompt(  )+reload(sesh list -z)' \
        --bind 'ctrl-f:change-prompt(  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
        --bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(  )+reload(sesh list)'
)"
