#!/bin/bash

function date_time() {

    printf "%s " "$(date +'%d-%b %I:%M:%S')"

}


function ip_address() {

    # Loop through the interfaces and check for the interface that is up.
    for file in /sys/class/net/*; do

        iface=$(basename $file);

        read status < $file/operstate;

        [ "$status" == "up" ] && ip addr show $iface | awk '/inet /{printf $2" "}'

    done

}

main ()
{
    ip_address
    date_time
}

main
